# Generated by Django 4.2 on 2026-06-01 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0002_alter_pokemon_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='type',
            field=models.CharField(choices=[('T', 'Tierra'), ('P', 'Planta'), ('E', 'Electrico'), ('A', 'Agua'), ('L', 'Lucha'), ('F', 'Fuego')], max_length=50),
        ),
    ]
