# Generated by Django 4.2 on 2026-06-09 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0004_alter_pokemon_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='type',
            field=models.CharField(choices=[('L', 'Lucha'), ('E', 'Electrico'), ('P', 'Planta'), ('T', 'Tierra'), ('F', 'Fuego'), ('A', 'Agua')], max_length=50),
        ),
    ]
